# Generated by Django 4.2.1 on 2023-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "complete",
                    models.BooleanField(default=False, verbose_name="Is completed"),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
        ),
    ]
